---
title: "Religion and well-being"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Background
In this study, called the Many Analysts Religion Project, or MARP, we investigated if religiosity was associated with increased well-being. 

We measured well-being in several ways: we were interested in physical, psychological, social and overall well-being. In this task, you need to run several linear regression analyses for each type of well-being in question.

## Original study
https://www.researchgate.net/publication/361844635_A_many-analysts_approach_to_the_relation_between_religiosity_and_well-being

## Codebook
`codebooks/marp_codebook.txt`

# Task

1) Build models
Check the codebook for the names of outcomes and predictors.  
You need to build linear regression models for each outcome. The models should contain each well-being variable separately, i.e. you need separate models for each outcome. You do not need to use the `country`, `cnorm_mean` and `ethnicity` variables.
An example model would look like: `wb_overall_mean ~ gender + age + education + religiosity`

2) Create tables that contains all parameter estimates, std. errors, t statistics, and p values.


#Solution
```{r setup}
library(tidyverse)
marp_data <- read_csv(here::here("data/marp_data.csv"))
```

#Building the models


#Printing the tables